/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBookingsRouteImport } from './routes/_app/bookings'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads.index'
import { Route as ApiPublicSeedRouteImport } from './routes/api/public/seed'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads.$leadId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const ApiPublicSeedRoute = ApiPublicSeedRouteImport.update({
  id: '/api/public/seed',
  path: '/api/public/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AppBookingsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/more': typeof AppMoreRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/transfers': typeof AppTransfersRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/leads/': typeof AppLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AppBookingsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/more': typeof AppMoreRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/transfers': typeof AppTransfersRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/leads': typeof AppLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/more': typeof AppMoreRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/bookings'
    | '/calendar'
    | '/dashboard'
    | '/leads'
    | '/more'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/transfers'
    | '/leads/$leadId'
    | '/api/public/seed'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/bookings'
    | '/calendar'
    | '/dashboard'
    | '/more'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/transfers'
    | '/leads/$leadId'
    | '/api/public/seed'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/bookings'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/leads'
    | '/_app/more'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/transfers'
    | '/_app/leads/$leadId'
    | '/api/public/seed'
    | '/_app/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicSeedRoute: typeof ApiPublicSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/api/public/seed': {
      id: '/api/public/seed'
      path: '/api/public/seed'
      fullPath: '/api/public/seed'
      preLoaderRoute: typeof ApiPublicSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMoreRoute: typeof AppMoreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTransfersRoute: typeof AppTransfersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMoreRoute: AppMoreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTransfersRoute: AppTransfersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicSeedRoute: ApiPublicSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
