/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorStatusTokenRouteImport } from './routes/vendor-status.$token'
import { Route as QuotationTokenRouteImport } from './routes/quotation.$token'
import { Route as PaymentTokenRouteImport } from './routes/payment.$token'
import { Route as InvoiceTokenRouteImport } from './routes/invoice.$token'
import { Route as FeedbackBookingIdRouteImport } from './routes/feedback.$bookingId'
import { Route as EventStatusTokenRouteImport } from './routes/event-status.$token'
import { Route as CoordinateTokenRouteImport } from './routes/coordinate.$token'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppStaleLeadsRouteImport } from './routes/_app/stale-leads'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppQuotationsRouteImport } from './routes/_app/quotations'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppNotInterestedRouteImport } from './routes/_app/not-interested'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCommandCentreRouteImport } from './routes/_app/command-centre'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBookingsRouteImport } from './routes/_app/bookings'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads.index'
import { Route as ApiPublicSeedRouteImport } from './routes/api/public/seed'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads.$leadId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers.$customerId'
import { Route as AppCompanySettingsCompanyIdRouteImport } from './routes/_app/company-settings.$companyId'
import { Route as AppCompanyDashboardCompanyIdRouteImport } from './routes/_app/company-dashboard.$companyId'
import { Route as ApiPublicHooksTaskRemindersRouteImport } from './routes/api/public/hooks/task-reminders'
import { Route as ApiPublicHooksStaleLeadScanRouteImport } from './routes/api/public/hooks/stale-lead-scan'
import { Route as ApiPublicHooksQuotationExpiryRouteImport } from './routes/api/public/hooks/quotation-expiry'
import { Route as ApiPublicHooksPreEventRemindersRouteImport } from './routes/api/public/hooks/pre-event-reminders'
import { Route as ApiPublicHooksPostEventAutomationRouteImport } from './routes/api/public/hooks/post-event-automation'
import { Route as ApiPublicHooksExpireQuotationsRouteImport } from './routes/api/public/hooks/expire-quotations'
import { Route as ApiPublicHooksCustomTaskRemindersRouteImport } from './routes/api/public/hooks/custom-task-reminders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorStatusTokenRoute = VendorStatusTokenRouteImport.update({
  id: '/vendor-status/$token',
  path: '/vendor-status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationTokenRoute = QuotationTokenRouteImport.update({
  id: '/quotation/$token',
  path: '/quotation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentTokenRoute = PaymentTokenRouteImport.update({
  id: '/payment/$token',
  path: '/payment/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTokenRoute = InvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackBookingIdRoute = FeedbackBookingIdRouteImport.update({
  id: '/feedback/$bookingId',
  path: '/feedback/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventStatusTokenRoute = EventStatusTokenRouteImport.update({
  id: '/event-status/$token',
  path: '/event-status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinateTokenRoute = CoordinateTokenRouteImport.update({
  id: '/coordinate/$token',
  path: '/coordinate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStaleLeadsRoute = AppStaleLeadsRouteImport.update({
  id: '/stale-leads',
  path: '/stale-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotInterestedRoute = AppNotInterestedRouteImport.update({
  id: '/not-interested',
  path: '/not-interested',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandCentreRoute = AppCommandCentreRouteImport.update({
  id: '/command-centre',
  path: '/command-centre',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const ApiPublicSeedRoute = ApiPublicSeedRouteImport.update({
  id: '/api/public/seed',
  path: '/api/public/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCompanySettingsCompanyIdRoute =
  AppCompanySettingsCompanyIdRouteImport.update({
    id: '/company-settings/$companyId',
    path: '/company-settings/$companyId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompanyDashboardCompanyIdRoute =
  AppCompanyDashboardCompanyIdRouteImport.update({
    id: '/company-dashboard/$companyId',
    path: '/company-dashboard/$companyId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksTaskRemindersRoute =
  ApiPublicHooksTaskRemindersRouteImport.update({
    id: '/api/public/hooks/task-reminders',
    path: '/api/public/hooks/task-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStaleLeadScanRoute =
  ApiPublicHooksStaleLeadScanRouteImport.update({
    id: '/api/public/hooks/stale-lead-scan',
    path: '/api/public/hooks/stale-lead-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksQuotationExpiryRoute =
  ApiPublicHooksQuotationExpiryRouteImport.update({
    id: '/api/public/hooks/quotation-expiry',
    path: '/api/public/hooks/quotation-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPreEventRemindersRoute =
  ApiPublicHooksPreEventRemindersRouteImport.update({
    id: '/api/public/hooks/pre-event-reminders',
    path: '/api/public/hooks/pre-event-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPostEventAutomationRoute =
  ApiPublicHooksPostEventAutomationRouteImport.update({
    id: '/api/public/hooks/post-event-automation',
    path: '/api/public/hooks/post-event-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireQuotationsRoute =
  ApiPublicHooksExpireQuotationsRouteImport.update({
    id: '/api/public/hooks/expire-quotations',
    path: '/api/public/hooks/expire-quotations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCustomTaskRemindersRoute =
  ApiPublicHooksCustomTaskRemindersRouteImport.update({
    id: '/api/public/hooks/custom-task-reminders',
    path: '/api/public/hooks/custom-task-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AppBookingsRoute
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRoute
  '/command-centre': typeof AppCommandCentreRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/more': typeof AppMoreRoute
  '/not-interested': typeof AppNotInterestedRoute
  '/notifications': typeof AppNotificationsRoute
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/stale-leads': typeof AppStaleLeadsRoute
  '/tasks': typeof AppTasksRoute
  '/transfers': typeof AppTransfersRoute
  '/coordinate/$token': typeof CoordinateTokenRoute
  '/event-status/$token': typeof EventStatusTokenRoute
  '/feedback/$bookingId': typeof FeedbackBookingIdRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/payment/$token': typeof PaymentTokenRoute
  '/quotation/$token': typeof QuotationTokenRoute
  '/vendor-status/$token': typeof VendorStatusTokenRoute
  '/company-dashboard/$companyId': typeof AppCompanyDashboardCompanyIdRoute
  '/company-settings/$companyId': typeof AppCompanySettingsCompanyIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/api/public/hooks/custom-task-reminders': typeof ApiPublicHooksCustomTaskRemindersRoute
  '/api/public/hooks/expire-quotations': typeof ApiPublicHooksExpireQuotationsRoute
  '/api/public/hooks/post-event-automation': typeof ApiPublicHooksPostEventAutomationRoute
  '/api/public/hooks/pre-event-reminders': typeof ApiPublicHooksPreEventRemindersRoute
  '/api/public/hooks/quotation-expiry': typeof ApiPublicHooksQuotationExpiryRoute
  '/api/public/hooks/stale-lead-scan': typeof ApiPublicHooksStaleLeadScanRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AppBookingsRoute
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRoute
  '/command-centre': typeof AppCommandCentreRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/more': typeof AppMoreRoute
  '/not-interested': typeof AppNotInterestedRoute
  '/notifications': typeof AppNotificationsRoute
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/stale-leads': typeof AppStaleLeadsRoute
  '/tasks': typeof AppTasksRoute
  '/transfers': typeof AppTransfersRoute
  '/coordinate/$token': typeof CoordinateTokenRoute
  '/event-status/$token': typeof EventStatusTokenRoute
  '/feedback/$bookingId': typeof FeedbackBookingIdRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/payment/$token': typeof PaymentTokenRoute
  '/quotation/$token': typeof QuotationTokenRoute
  '/vendor-status/$token': typeof VendorStatusTokenRoute
  '/company-dashboard/$companyId': typeof AppCompanyDashboardCompanyIdRoute
  '/company-settings/$companyId': typeof AppCompanySettingsCompanyIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/leads': typeof AppLeadsIndexRoute
  '/api/public/hooks/custom-task-reminders': typeof ApiPublicHooksCustomTaskRemindersRoute
  '/api/public/hooks/expire-quotations': typeof ApiPublicHooksExpireQuotationsRoute
  '/api/public/hooks/post-event-automation': typeof ApiPublicHooksPostEventAutomationRoute
  '/api/public/hooks/pre-event-reminders': typeof ApiPublicHooksPreEventRemindersRoute
  '/api/public/hooks/quotation-expiry': typeof ApiPublicHooksQuotationExpiryRoute
  '/api/public/hooks/stale-lead-scan': typeof ApiPublicHooksStaleLeadScanRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/command-centre': typeof AppCommandCentreRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/more': typeof AppMoreRoute
  '/_app/not-interested': typeof AppNotInterestedRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stale-leads': typeof AppStaleLeadsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/coordinate/$token': typeof CoordinateTokenRoute
  '/event-status/$token': typeof EventStatusTokenRoute
  '/feedback/$bookingId': typeof FeedbackBookingIdRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/payment/$token': typeof PaymentTokenRoute
  '/quotation/$token': typeof QuotationTokenRoute
  '/vendor-status/$token': typeof VendorStatusTokenRoute
  '/_app/company-dashboard/$companyId': typeof AppCompanyDashboardCompanyIdRoute
  '/_app/company-settings/$companyId': typeof AppCompanySettingsCompanyIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/api/public/hooks/custom-task-reminders': typeof ApiPublicHooksCustomTaskRemindersRoute
  '/api/public/hooks/expire-quotations': typeof ApiPublicHooksExpireQuotationsRoute
  '/api/public/hooks/post-event-automation': typeof ApiPublicHooksPostEventAutomationRoute
  '/api/public/hooks/pre-event-reminders': typeof ApiPublicHooksPreEventRemindersRoute
  '/api/public/hooks/quotation-expiry': typeof ApiPublicHooksQuotationExpiryRoute
  '/api/public/hooks/stale-lead-scan': typeof ApiPublicHooksStaleLeadScanRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/bookings'
    | '/calendar'
    | '/campaigns'
    | '/command-centre'
    | '/customers'
    | '/dashboard'
    | '/feedback'
    | '/leads'
    | '/more'
    | '/not-interested'
    | '/notifications'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/stale-leads'
    | '/tasks'
    | '/transfers'
    | '/coordinate/$token'
    | '/event-status/$token'
    | '/feedback/$bookingId'
    | '/invoice/$token'
    | '/payment/$token'
    | '/quotation/$token'
    | '/vendor-status/$token'
    | '/company-dashboard/$companyId'
    | '/company-settings/$companyId'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/api/public/seed'
    | '/leads/'
    | '/api/public/hooks/custom-task-reminders'
    | '/api/public/hooks/expire-quotations'
    | '/api/public/hooks/post-event-automation'
    | '/api/public/hooks/pre-event-reminders'
    | '/api/public/hooks/quotation-expiry'
    | '/api/public/hooks/stale-lead-scan'
    | '/api/public/hooks/task-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/bookings'
    | '/calendar'
    | '/campaigns'
    | '/command-centre'
    | '/customers'
    | '/dashboard'
    | '/feedback'
    | '/more'
    | '/not-interested'
    | '/notifications'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/stale-leads'
    | '/tasks'
    | '/transfers'
    | '/coordinate/$token'
    | '/event-status/$token'
    | '/feedback/$bookingId'
    | '/invoice/$token'
    | '/payment/$token'
    | '/quotation/$token'
    | '/vendor-status/$token'
    | '/company-dashboard/$companyId'
    | '/company-settings/$companyId'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/api/public/seed'
    | '/leads'
    | '/api/public/hooks/custom-task-reminders'
    | '/api/public/hooks/expire-quotations'
    | '/api/public/hooks/post-event-automation'
    | '/api/public/hooks/pre-event-reminders'
    | '/api/public/hooks/quotation-expiry'
    | '/api/public/hooks/stale-lead-scan'
    | '/api/public/hooks/task-reminders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/bookings'
    | '/_app/calendar'
    | '/_app/campaigns'
    | '/_app/command-centre'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/leads'
    | '/_app/more'
    | '/_app/not-interested'
    | '/_app/notifications'
    | '/_app/quotations'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/stale-leads'
    | '/_app/tasks'
    | '/_app/transfers'
    | '/coordinate/$token'
    | '/event-status/$token'
    | '/feedback/$bookingId'
    | '/invoice/$token'
    | '/payment/$token'
    | '/quotation/$token'
    | '/vendor-status/$token'
    | '/_app/company-dashboard/$companyId'
    | '/_app/company-settings/$companyId'
    | '/_app/customers/$customerId'
    | '/_app/leads/$leadId'
    | '/api/public/seed'
    | '/_app/leads/'
    | '/api/public/hooks/custom-task-reminders'
    | '/api/public/hooks/expire-quotations'
    | '/api/public/hooks/post-event-automation'
    | '/api/public/hooks/pre-event-reminders'
    | '/api/public/hooks/quotation-expiry'
    | '/api/public/hooks/stale-lead-scan'
    | '/api/public/hooks/task-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CoordinateTokenRoute: typeof CoordinateTokenRoute
  EventStatusTokenRoute: typeof EventStatusTokenRoute
  FeedbackBookingIdRoute: typeof FeedbackBookingIdRoute
  InvoiceTokenRoute: typeof InvoiceTokenRoute
  PaymentTokenRoute: typeof PaymentTokenRoute
  QuotationTokenRoute: typeof QuotationTokenRoute
  VendorStatusTokenRoute: typeof VendorStatusTokenRoute
  ApiPublicSeedRoute: typeof ApiPublicSeedRoute
  ApiPublicHooksCustomTaskRemindersRoute: typeof ApiPublicHooksCustomTaskRemindersRoute
  ApiPublicHooksExpireQuotationsRoute: typeof ApiPublicHooksExpireQuotationsRoute
  ApiPublicHooksPostEventAutomationRoute: typeof ApiPublicHooksPostEventAutomationRoute
  ApiPublicHooksPreEventRemindersRoute: typeof ApiPublicHooksPreEventRemindersRoute
  ApiPublicHooksQuotationExpiryRoute: typeof ApiPublicHooksQuotationExpiryRoute
  ApiPublicHooksStaleLeadScanRoute: typeof ApiPublicHooksStaleLeadScanRoute
  ApiPublicHooksTaskRemindersRoute: typeof ApiPublicHooksTaskRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-status/$token': {
      id: '/vendor-status/$token'
      path: '/vendor-status/$token'
      fullPath: '/vendor-status/$token'
      preLoaderRoute: typeof VendorStatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation/$token': {
      id: '/quotation/$token'
      path: '/quotation/$token'
      fullPath: '/quotation/$token'
      preLoaderRoute: typeof QuotationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$token': {
      id: '/payment/$token'
      path: '/payment/$token'
      fullPath: '/payment/$token'
      preLoaderRoute: typeof PaymentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$token': {
      id: '/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/invoice/$token'
      preLoaderRoute: typeof InvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$bookingId': {
      id: '/feedback/$bookingId'
      path: '/feedback/$bookingId'
      fullPath: '/feedback/$bookingId'
      preLoaderRoute: typeof FeedbackBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-status/$token': {
      id: '/event-status/$token'
      path: '/event-status/$token'
      fullPath: '/event-status/$token'
      preLoaderRoute: typeof EventStatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinate/$token': {
      id: '/coordinate/$token'
      path: '/coordinate/$token'
      fullPath: '/coordinate/$token'
      preLoaderRoute: typeof CoordinateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stale-leads': {
      id: '/_app/stale-leads'
      path: '/stale-leads'
      fullPath: '/stale-leads'
      preLoaderRoute: typeof AppStaleLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/not-interested': {
      id: '/_app/not-interested'
      path: '/not-interested'
      fullPath: '/not-interested'
      preLoaderRoute: typeof AppNotInterestedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command-centre': {
      id: '/_app/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof AppCommandCentreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/api/public/seed': {
      id: '/api/public/seed'
      path: '/api/public/seed'
      fullPath: '/api/public/seed'
      preLoaderRoute: typeof ApiPublicSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/company-settings/$companyId': {
      id: '/_app/company-settings/$companyId'
      path: '/company-settings/$companyId'
      fullPath: '/company-settings/$companyId'
      preLoaderRoute: typeof AppCompanySettingsCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company-dashboard/$companyId': {
      id: '/_app/company-dashboard/$companyId'
      path: '/company-dashboard/$companyId'
      fullPath: '/company-dashboard/$companyId'
      preLoaderRoute: typeof AppCompanyDashboardCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/task-reminders': {
      id: '/api/public/hooks/task-reminders'
      path: '/api/public/hooks/task-reminders'
      fullPath: '/api/public/hooks/task-reminders'
      preLoaderRoute: typeof ApiPublicHooksTaskRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stale-lead-scan': {
      id: '/api/public/hooks/stale-lead-scan'
      path: '/api/public/hooks/stale-lead-scan'
      fullPath: '/api/public/hooks/stale-lead-scan'
      preLoaderRoute: typeof ApiPublicHooksStaleLeadScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/quotation-expiry': {
      id: '/api/public/hooks/quotation-expiry'
      path: '/api/public/hooks/quotation-expiry'
      fullPath: '/api/public/hooks/quotation-expiry'
      preLoaderRoute: typeof ApiPublicHooksQuotationExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pre-event-reminders': {
      id: '/api/public/hooks/pre-event-reminders'
      path: '/api/public/hooks/pre-event-reminders'
      fullPath: '/api/public/hooks/pre-event-reminders'
      preLoaderRoute: typeof ApiPublicHooksPreEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/post-event-automation': {
      id: '/api/public/hooks/post-event-automation'
      path: '/api/public/hooks/post-event-automation'
      fullPath: '/api/public/hooks/post-event-automation'
      preLoaderRoute: typeof ApiPublicHooksPostEventAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-quotations': {
      id: '/api/public/hooks/expire-quotations'
      path: '/api/public/hooks/expire-quotations'
      fullPath: '/api/public/hooks/expire-quotations'
      preLoaderRoute: typeof ApiPublicHooksExpireQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/custom-task-reminders': {
      id: '/api/public/hooks/custom-task-reminders'
      path: '/api/public/hooks/custom-task-reminders'
      fullPath: '/api/public/hooks/custom-task-reminders'
      preLoaderRoute: typeof ApiPublicHooksCustomTaskRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppCommandCentreRoute: typeof AppCommandCentreRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMoreRoute: typeof AppMoreRoute
  AppNotInterestedRoute: typeof AppNotInterestedRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaleLeadsRoute: typeof AppStaleLeadsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppCompanyDashboardCompanyIdRoute: typeof AppCompanyDashboardCompanyIdRoute
  AppCompanySettingsCompanyIdRoute: typeof AppCompanySettingsCompanyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppCommandCentreRoute: AppCommandCentreRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMoreRoute: AppMoreRoute,
  AppNotInterestedRoute: AppNotInterestedRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaleLeadsRoute: AppStaleLeadsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppCompanyDashboardCompanyIdRoute: AppCompanyDashboardCompanyIdRoute,
  AppCompanySettingsCompanyIdRoute: AppCompanySettingsCompanyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CoordinateTokenRoute: CoordinateTokenRoute,
  EventStatusTokenRoute: EventStatusTokenRoute,
  FeedbackBookingIdRoute: FeedbackBookingIdRoute,
  InvoiceTokenRoute: InvoiceTokenRoute,
  PaymentTokenRoute: PaymentTokenRoute,
  QuotationTokenRoute: QuotationTokenRoute,
  VendorStatusTokenRoute: VendorStatusTokenRoute,
  ApiPublicSeedRoute: ApiPublicSeedRoute,
  ApiPublicHooksCustomTaskRemindersRoute:
    ApiPublicHooksCustomTaskRemindersRoute,
  ApiPublicHooksExpireQuotationsRoute: ApiPublicHooksExpireQuotationsRoute,
  ApiPublicHooksPostEventAutomationRoute:
    ApiPublicHooksPostEventAutomationRoute,
  ApiPublicHooksPreEventRemindersRoute: ApiPublicHooksPreEventRemindersRoute,
  ApiPublicHooksQuotationExpiryRoute: ApiPublicHooksQuotationExpiryRoute,
  ApiPublicHooksStaleLeadScanRoute: ApiPublicHooksStaleLeadScanRoute,
  ApiPublicHooksTaskRemindersRoute: ApiPublicHooksTaskRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
